services:
  # PostgreSQL DB
  postgres:
    image: postgres:16-alpine
    container_name: template-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-templatedb}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - template-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 6


  # Spring boot application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-templatedb}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL:-true}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - template-network

  adminer:
    image: adminer:latest
    container_name: template-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    networks:
      - template-network
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres-data:
    driver: local

networks:
  template-network:
    driver: bridge